[project]
name = "munnokki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "appdata>=2.2.1",
    "cartopy>=0.25.0",
    "caseutil>=0.7.2",
    "cdsapi>=0.7.7",
    "dask>=2026.7.1",
    "flox>=0.11.2",
    "gdal>=3.13.2",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "owslib>=0.36.0",
    "patool>=4.0.5",
    "pybtex>=0.26.1",
    "pybtexris>=0.2.0",
    "rarfile>=4.5",
    "requests>=2.34.2",
    "rioxarray>=0.23.0",
    "scipy>=1.18.0",
    "soilgrids>=0.1.5",
    "xarray>=2026.7.0",
    "xarray-regrid>=0.4.2",
]


[tool.uv]
required-environments = [
  "python_version >= '3.14'",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "scipy-stubs~=1.18.0",
]
