அமில_காரத்தன்மை = "அமில காரத்தன்மை"
களிமண் = "களிமண்"
கரம்பை = "கரம்பை"
மணல் = "மணல்"
அடர்த்தி = "அடர்த்தி"
பாறைத்_துண்டங்கள் = "பாறைத் துண்டங்கள்"
கன_நீர்_இருப்பு_பத்து = "கன நீர் இருப்பு ௰"
கன_நீர்_இருப்பு_மூப்பத்துமூன்று = "கன நீர் இருப்பு ௩௰ ௩"
கன_நீர்_இருப்பு_ஆயிரத்தியைநூறு = "கன நீர் இருப்பு ௲௫௱"
கரிம_சேர்ம_அடர்த்தி = "கரிம_சேர்ம_அடர்த்தி"
நேர்மின்_அயனி_பறிமாற்ற_தன்மை = "நேர்மின்_அயனி_பறிமாற்ற_தன்மை"
தலைச்சத்து = "தலைச்சத்து"
மண்_கரிம_சத்து = "மண்_கரிம_சத்து"

"bdod 	Bulk density 	cg/cm3 	100 	kg/dm3"
"cec 	CEC buffered at pH7 	mmol(c)/kg 	10 	cmol(c)/kg"
"cfvo 	Coarse fragments 	cm3/dm3 (vol‰) 	10 	cm3/100cm3 (vol%)"
"clay 	Clay 	g/kg 	10 	g/100g (%)"
"nitrogen 	Nitrogen 	cg/kg 	100 	g/kg"
"ocd 	Organic carbon density 	hg/m3 	10 	kg/m3"
"ocs 	Organic carbon stocks 	t/ha 	10 	kg/m2"
"soc 	Soil organic carbon 	dg/kg 	10 	g/kg"
"phh2o 	pH water 	pH x 10 	10 	-"
"sand 	Sand 	g/kg 	10 	g/100g (%)"
"silt 	Silt 	g/kg 	10 	g/100g (%)"
"wv0010 	Volumetric Water Content at 10kPa 	10-3 cm3cm-3 (0.1 v% or 1 mm/m) 	10 	10−2 cm3 cm−3 (%)"
"wv1500 	Volumetric Water Content at 1500kPa 	10-3 cm3cm-3 (0.1 v% or 1 mm/m) 	10 	10−2 cm3 cm−3 (%)"
"wv003 	Volumetric Water Content at 33kPa 	10-3 cm3cm-3 (0.1 v% or 1 mm/m) 	10 	10−2 cm3 cm−3 (%)"